= Opal::Webassembly

WebAssembly support for Opal.

== Opal Upstreaming
Please refer to https://github.com/webdev778/interscript/blob/master/opal-onigmo.md#opal-webassembly[here]

== Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'opal-webassembly'
----

And then execute:

[source,sh]
----
$ bundle install
----

Or install it yourself as:

[source,sh]
----
$ gem install opal-onigmo
----


== Usage

Please see `examples/simple_ffi` for basic usage.

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake spec` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to https://rubygems.org[rubygems.org].

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/hmdne/opal-webassembly.

== License

The gem is available as open source under the terms of the BSD 2-clause license.
